// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Calculator.proto

package loull.hadoop.pb.rpc2;

public final class CalculatorPbWrapper {
  private CalculatorPbWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CalculatorRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 x = 1;
    /**
     * <code>required int32 x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 1;</code>
     */
    int getX();

    // required int32 y = 2;
    /**
     * <code>required int32 y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required int32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code CalculatorRequestProto}
   */
  public static final class CalculatorRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements CalculatorRequestProtoOrBuilder {
    // Use CalculatorRequestProto.newBuilder() to construct.
    private CalculatorRequestProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalculatorRequestProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalculatorRequestProto defaultInstance;
    public static CalculatorRequestProto getDefaultInstance() {
      return defaultInstance;
    }

    public CalculatorRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalculatorRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto.class, loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto.Builder.class);
    }

    public static com.google.protobuf.Parser<CalculatorRequestProto> PARSER =
        new com.google.protobuf.AbstractParser<CalculatorRequestProto>() {
      public CalculatorRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalculatorRequestProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalculatorRequestProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>required int32 x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    // required int32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>required int32 y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalculatorRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto.class, loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto.Builder.class);
      }

      // Construct using loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorRequestProto_descriptor;
      }

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto getDefaultInstanceForType() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto.getDefaultInstance();
      }

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto build() {
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto buildPartial() {
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto result = new loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto) {
          return mergeFrom((loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto other) {
        if (other == loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 x = 1;
      private int x_ ;
      /**
       * <code>required int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      // required int32 y = 2;
      private int y_ ;
      /**
       * <code>required int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CalculatorRequestProto)
    }

    static {
      defaultInstance = new CalculatorRequestProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CalculatorRequestProto)
  }

  public interface CalculatorResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 value = 1;
    /**
     * <code>required int32 value = 1;</code>
     */
    boolean hasValue();
    /**
     * <code>required int32 value = 1;</code>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code CalculatorResponseProto}
   */
  public static final class CalculatorResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements CalculatorResponseProtoOrBuilder {
    // Use CalculatorResponseProto.newBuilder() to construct.
    private CalculatorResponseProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalculatorResponseProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalculatorResponseProto defaultInstance;
    public static CalculatorResponseProto getDefaultInstance() {
      return defaultInstance;
    }

    public CalculatorResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalculatorResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorResponseProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.class, loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.Builder.class);
    }

    public static com.google.protobuf.Parser<CalculatorResponseProto> PARSER =
        new com.google.protobuf.AbstractParser<CalculatorResponseProto>() {
      public CalculatorResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalculatorResponseProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalculatorResponseProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    /**
     * <code>required int32 value = 1;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 value = 1;</code>
     */
    public int getValue() {
      return value_;
    }

    private void initFields() {
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalculatorResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorResponseProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.class, loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.Builder.class);
      }

      // Construct using loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorResponseProto_descriptor;
      }

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto getDefaultInstanceForType() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.getDefaultInstance();
      }

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto build() {
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto buildPartial() {
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto result = new loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto) {
          return mergeFrom((loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto other) {
        if (other == loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 value = 1;
      private int value_ ;
      /**
       * <code>required int32 value = 1;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 value = 1;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>required int32 value = 1;</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 value = 1;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CalculatorResponseProto)
    }

    static {
      defaultInstance = new CalculatorResponseProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CalculatorResponseProto)
  }

  public interface CalculatorIncRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 x = 1;
    /**
     * <code>required int32 x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 1;</code>
     */
    int getX();
  }
  /**
   * Protobuf type {@code CalculatorIncRequestProto}
   */
  public static final class CalculatorIncRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements CalculatorIncRequestProtoOrBuilder {
    // Use CalculatorIncRequestProto.newBuilder() to construct.
    private CalculatorIncRequestProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalculatorIncRequestProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalculatorIncRequestProto defaultInstance;
    public static CalculatorIncRequestProto getDefaultInstance() {
      return defaultInstance;
    }

    public CalculatorIncRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalculatorIncRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorIncRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorIncRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto.class, loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto.Builder.class);
    }

    public static com.google.protobuf.Parser<CalculatorIncRequestProto> PARSER =
        new com.google.protobuf.AbstractParser<CalculatorIncRequestProto>() {
      public CalculatorIncRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalculatorIncRequestProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalculatorIncRequestProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>required int32 x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    private void initFields() {
      x_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalculatorIncRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorIncRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorIncRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto.class, loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto.Builder.class);
      }

      // Construct using loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.internal_static_CalculatorIncRequestProto_descriptor;
      }

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto getDefaultInstanceForType() {
        return loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto.getDefaultInstance();
      }

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto build() {
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto buildPartial() {
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto result = new loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto) {
          return mergeFrom((loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto other) {
        if (other == loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorIncRequestProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 x = 1;
      private int x_ ;
      /**
       * <code>required int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CalculatorIncRequestProto)
    }

    static {
      defaultInstance = new CalculatorIncRequestProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CalculatorIncRequestProto)
  }

  /**
   * Protobuf service {@code CalculateService}
   */
  public static abstract class CalculateService
      implements com.google.protobuf.Service {
    protected CalculateService() {}

    public interface Interface {
      /**
       * <code>rpc add(.CalculatorRequestProto) returns (.CalculatorResponseProto);</code>
       */
      public abstract void add(
          com.google.protobuf.RpcController controller,
          loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto request,
          com.google.protobuf.RpcCallback<loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CalculateService() {
        @java.lang.Override
        public  void add(
            com.google.protobuf.RpcController controller,
            loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto request,
            com.google.protobuf.RpcCallback<loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto> done) {
          impl.add(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.add(controller, (loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc add(.CalculatorRequestProto) returns (.CalculatorResponseProto);</code>
     */
    public abstract void add(
        com.google.protobuf.RpcController controller,
        loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto request,
        com.google.protobuf.RpcCallback<loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return loull.hadoop.pb.rpc2.CalculatorPbWrapper.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.add(controller, (loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto)request,
            com.google.protobuf.RpcUtil.<loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculateService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void add(
          com.google.protobuf.RpcController controller,
          loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto request,
          com.google.protobuf.RpcCallback<loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.class,
            loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto add(
          com.google.protobuf.RpcController controller,
          loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto add(
          com.google.protobuf.RpcController controller,
          loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          loull.hadoop.pb.rpc2.CalculatorPbWrapper.CalculatorResponseProto.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:CalculateService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculatorRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CalculatorRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculatorResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CalculatorResponseProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculatorIncRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CalculatorIncRequestProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Calculator.proto\".\n\026CalculatorRequestP" +
      "roto\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005\"(\n\027Calculator" +
      "ResponseProto\022\r\n\005value\030\001 \002(\005\"&\n\031Calculat" +
      "orIncRequestProto\022\t\n\001x\030\001 \002(\0052L\n\020Calculat" +
      "eService\0228\n\003add\022\027.CalculatorRequestProto" +
      "\032\030.CalculatorResponseProtoB.\n\024loull.hado" +
      "op.pb.rpc2B\023CalculatorPbWrapper\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CalculatorRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CalculatorRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CalculatorRequestProto_descriptor,
              new java.lang.String[] { "X", "Y", });
          internal_static_CalculatorResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CalculatorResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CalculatorResponseProto_descriptor,
              new java.lang.String[] { "Value", });
          internal_static_CalculatorIncRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_CalculatorIncRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CalculatorIncRequestProto_descriptor,
              new java.lang.String[] { "X", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
