// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoullRPCService.proto

package loull.pb.rpc;

public final class LoullRPCService {
  private LoullRPCService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string agent = 1;
    /**
     * <code>required string agent = 1;</code>
     */
    boolean hasAgent();
    /**
     * <code>required string agent = 1;</code>
     */
    java.lang.String getAgent();
    /**
     * <code>required string agent = 1;</code>
     */
    com.google.protobuf.ByteString
        getAgentBytes();

    // required int32 thresh = 2;
    /**
     * <code>required int32 thresh = 2;</code>
     */
    boolean hasThresh();
    /**
     * <code>required int32 thresh = 2;</code>
     */
    int getThresh();
  }
  /**
   * Protobuf type {@code loull.pb.rpc.LoRequest}
   */
  public static final class LoRequest extends
      com.google.protobuf.GeneratedMessage
      implements LoRequestOrBuilder {
    // Use LoRequest.newBuilder() to construct.
    private LoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoRequest defaultInstance;
    public static LoRequest getDefaultInstance() {
      return defaultInstance;
    }

    public LoRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              agent_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              thresh_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              loull.pb.rpc.LoullRPCService.LoRequest.class, loull.pb.rpc.LoullRPCService.LoRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<LoRequest> PARSER =
        new com.google.protobuf.AbstractParser<LoRequest>() {
      public LoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string agent = 1;
    public static final int AGENT_FIELD_NUMBER = 1;
    private java.lang.Object agent_;
    /**
     * <code>required string agent = 1;</code>
     */
    public boolean hasAgent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string agent = 1;</code>
     */
    public java.lang.String getAgent() {
      java.lang.Object ref = agent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          agent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string agent = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAgentBytes() {
      java.lang.Object ref = agent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 thresh = 2;
    public static final int THRESH_FIELD_NUMBER = 2;
    private int thresh_;
    /**
     * <code>required int32 thresh = 2;</code>
     */
    public boolean hasThresh() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 thresh = 2;</code>
     */
    public int getThresh() {
      return thresh_;
    }

    private void initFields() {
      agent_ = "";
      thresh_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAgent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThresh()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAgentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, thresh_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAgentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, thresh_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static loull.pb.rpc.LoullRPCService.LoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.pb.rpc.LoullRPCService.LoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.pb.rpc.LoullRPCService.LoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.pb.rpc.LoullRPCService.LoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.pb.rpc.LoullRPCService.LoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.pb.rpc.LoullRPCService.LoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static loull.pb.rpc.LoullRPCService.LoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static loull.pb.rpc.LoullRPCService.LoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static loull.pb.rpc.LoullRPCService.LoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.pb.rpc.LoullRPCService.LoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(loull.pb.rpc.LoullRPCService.LoRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code loull.pb.rpc.LoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements loull.pb.rpc.LoullRPCService.LoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                loull.pb.rpc.LoullRPCService.LoRequest.class, loull.pb.rpc.LoullRPCService.LoRequest.Builder.class);
      }

      // Construct using loull.pb.rpc.LoullRPCService.LoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        agent_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        thresh_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoRequest_descriptor;
      }

      public loull.pb.rpc.LoullRPCService.LoRequest getDefaultInstanceForType() {
        return loull.pb.rpc.LoullRPCService.LoRequest.getDefaultInstance();
      }

      public loull.pb.rpc.LoullRPCService.LoRequest build() {
        loull.pb.rpc.LoullRPCService.LoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public loull.pb.rpc.LoullRPCService.LoRequest buildPartial() {
        loull.pb.rpc.LoullRPCService.LoRequest result = new loull.pb.rpc.LoullRPCService.LoRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.agent_ = agent_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.thresh_ = thresh_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof loull.pb.rpc.LoullRPCService.LoRequest) {
          return mergeFrom((loull.pb.rpc.LoullRPCService.LoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(loull.pb.rpc.LoullRPCService.LoRequest other) {
        if (other == loull.pb.rpc.LoullRPCService.LoRequest.getDefaultInstance()) return this;
        if (other.hasAgent()) {
          bitField0_ |= 0x00000001;
          agent_ = other.agent_;
          onChanged();
        }
        if (other.hasThresh()) {
          setThresh(other.getThresh());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAgent()) {
          
          return false;
        }
        if (!hasThresh()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        loull.pb.rpc.LoullRPCService.LoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (loull.pb.rpc.LoullRPCService.LoRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string agent = 1;
      private java.lang.Object agent_ = "";
      /**
       * <code>required string agent = 1;</code>
       */
      public boolean hasAgent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string agent = 1;</code>
       */
      public java.lang.String getAgent() {
        java.lang.Object ref = agent_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          agent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string agent = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAgentBytes() {
        java.lang.Object ref = agent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          agent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string agent = 1;</code>
       */
      public Builder setAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        agent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string agent = 1;</code>
       */
      public Builder clearAgent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        agent_ = getDefaultInstance().getAgent();
        onChanged();
        return this;
      }
      /**
       * <code>required string agent = 1;</code>
       */
      public Builder setAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        agent_ = value;
        onChanged();
        return this;
      }

      // required int32 thresh = 2;
      private int thresh_ ;
      /**
       * <code>required int32 thresh = 2;</code>
       */
      public boolean hasThresh() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 thresh = 2;</code>
       */
      public int getThresh() {
        return thresh_;
      }
      /**
       * <code>required int32 thresh = 2;</code>
       */
      public Builder setThresh(int value) {
        bitField0_ |= 0x00000002;
        thresh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 thresh = 2;</code>
       */
      public Builder clearThresh() {
        bitField0_ = (bitField0_ & ~0x00000002);
        thresh_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:loull.pb.rpc.LoRequest)
    }

    static {
      defaultInstance = new LoRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:loull.pb.rpc.LoRequest)
  }

  public interface LoResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 result = 1;
    /**
     * <code>required int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     */
    int getResult();

    // required string alert = 2;
    /**
     * <code>required string alert = 2;</code>
     */
    boolean hasAlert();
    /**
     * <code>required string alert = 2;</code>
     */
    java.lang.String getAlert();
    /**
     * <code>required string alert = 2;</code>
     */
    com.google.protobuf.ByteString
        getAlertBytes();
  }
  /**
   * Protobuf type {@code loull.pb.rpc.LoResponse}
   */
  public static final class LoResponse extends
      com.google.protobuf.GeneratedMessage
      implements LoResponseOrBuilder {
    // Use LoResponse.newBuilder() to construct.
    private LoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoResponse defaultInstance;
    public static LoResponse getDefaultInstance() {
      return defaultInstance;
    }

    public LoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              alert_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              loull.pb.rpc.LoullRPCService.LoResponse.class, loull.pb.rpc.LoullRPCService.LoResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<LoResponse> PARSER =
        new com.google.protobuf.AbstractParser<LoResponse>() {
      public LoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    // required string alert = 2;
    public static final int ALERT_FIELD_NUMBER = 2;
    private java.lang.Object alert_;
    /**
     * <code>required string alert = 2;</code>
     */
    public boolean hasAlert() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string alert = 2;</code>
     */
    public java.lang.String getAlert() {
      java.lang.Object ref = alert_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          alert_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string alert = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAlertBytes() {
      java.lang.Object ref = alert_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alert_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      result_ = 0;
      alert_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlert()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAlertBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAlertBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static loull.pb.rpc.LoullRPCService.LoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.pb.rpc.LoullRPCService.LoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.pb.rpc.LoullRPCService.LoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loull.pb.rpc.LoullRPCService.LoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loull.pb.rpc.LoullRPCService.LoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.pb.rpc.LoullRPCService.LoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static loull.pb.rpc.LoullRPCService.LoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static loull.pb.rpc.LoullRPCService.LoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static loull.pb.rpc.LoullRPCService.LoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static loull.pb.rpc.LoullRPCService.LoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(loull.pb.rpc.LoullRPCService.LoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code loull.pb.rpc.LoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements loull.pb.rpc.LoullRPCService.LoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                loull.pb.rpc.LoullRPCService.LoResponse.class, loull.pb.rpc.LoullRPCService.LoResponse.Builder.class);
      }

      // Construct using loull.pb.rpc.LoullRPCService.LoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        alert_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return loull.pb.rpc.LoullRPCService.internal_static_loull_pb_rpc_LoResponse_descriptor;
      }

      public loull.pb.rpc.LoullRPCService.LoResponse getDefaultInstanceForType() {
        return loull.pb.rpc.LoullRPCService.LoResponse.getDefaultInstance();
      }

      public loull.pb.rpc.LoullRPCService.LoResponse build() {
        loull.pb.rpc.LoullRPCService.LoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public loull.pb.rpc.LoullRPCService.LoResponse buildPartial() {
        loull.pb.rpc.LoullRPCService.LoResponse result = new loull.pb.rpc.LoullRPCService.LoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.alert_ = alert_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof loull.pb.rpc.LoullRPCService.LoResponse) {
          return mergeFrom((loull.pb.rpc.LoullRPCService.LoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(loull.pb.rpc.LoullRPCService.LoResponse other) {
        if (other == loull.pb.rpc.LoullRPCService.LoResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasAlert()) {
          bitField0_ |= 0x00000002;
          alert_ = other.alert_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (!hasAlert()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        loull.pb.rpc.LoullRPCService.LoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (loull.pb.rpc.LoullRPCService.LoResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 result = 1;
      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // required string alert = 2;
      private java.lang.Object alert_ = "";
      /**
       * <code>required string alert = 2;</code>
       */
      public boolean hasAlert() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string alert = 2;</code>
       */
      public java.lang.String getAlert() {
        java.lang.Object ref = alert_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          alert_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string alert = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAlertBytes() {
        java.lang.Object ref = alert_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alert_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string alert = 2;</code>
       */
      public Builder setAlert(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        alert_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string alert = 2;</code>
       */
      public Builder clearAlert() {
        bitField0_ = (bitField0_ & ~0x00000002);
        alert_ = getDefaultInstance().getAlert();
        onChanged();
        return this;
      }
      /**
       * <code>required string alert = 2;</code>
       */
      public Builder setAlertBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        alert_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:loull.pb.rpc.LoResponse)
    }

    static {
      defaultInstance = new LoResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:loull.pb.rpc.LoResponse)
  }

  /**
   * Protobuf service {@code loull.pb.rpc.MyService}
   */
  public static abstract class MyService
      implements com.google.protobuf.Service {
    protected MyService() {}

    public interface Interface {
      /**
       * <code>rpc loullSample(.loull.pb.rpc.LoRequest) returns (.loull.pb.rpc.LoResponse);</code>
       */
      public abstract void loullSample(
          com.google.protobuf.RpcController controller,
          loull.pb.rpc.LoullRPCService.LoRequest request,
          com.google.protobuf.RpcCallback<loull.pb.rpc.LoullRPCService.LoResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new MyService() {
        @java.lang.Override
        public  void loullSample(
            com.google.protobuf.RpcController controller,
            loull.pb.rpc.LoullRPCService.LoRequest request,
            com.google.protobuf.RpcCallback<loull.pb.rpc.LoullRPCService.LoResponse> done) {
          impl.loullSample(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.loullSample(controller, (loull.pb.rpc.LoullRPCService.LoRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return loull.pb.rpc.LoullRPCService.LoRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return loull.pb.rpc.LoullRPCService.LoResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc loullSample(.loull.pb.rpc.LoRequest) returns (.loull.pb.rpc.LoResponse);</code>
     */
    public abstract void loullSample(
        com.google.protobuf.RpcController controller,
        loull.pb.rpc.LoullRPCService.LoRequest request,
        com.google.protobuf.RpcCallback<loull.pb.rpc.LoullRPCService.LoResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return loull.pb.rpc.LoullRPCService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.loullSample(controller, (loull.pb.rpc.LoullRPCService.LoRequest)request,
            com.google.protobuf.RpcUtil.<loull.pb.rpc.LoullRPCService.LoResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return loull.pb.rpc.LoullRPCService.LoRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return loull.pb.rpc.LoullRPCService.LoResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends loull.pb.rpc.LoullRPCService.MyService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void loullSample(
          com.google.protobuf.RpcController controller,
          loull.pb.rpc.LoullRPCService.LoRequest request,
          com.google.protobuf.RpcCallback<loull.pb.rpc.LoullRPCService.LoResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          loull.pb.rpc.LoullRPCService.LoResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            loull.pb.rpc.LoullRPCService.LoResponse.class,
            loull.pb.rpc.LoullRPCService.LoResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public loull.pb.rpc.LoullRPCService.LoResponse loullSample(
          com.google.protobuf.RpcController controller,
          loull.pb.rpc.LoullRPCService.LoRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public loull.pb.rpc.LoullRPCService.LoResponse loullSample(
          com.google.protobuf.RpcController controller,
          loull.pb.rpc.LoullRPCService.LoRequest request)
          throws com.google.protobuf.ServiceException {
        return (loull.pb.rpc.LoullRPCService.LoResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          loull.pb.rpc.LoullRPCService.LoResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:loull.pb.rpc.MyService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_loull_pb_rpc_LoRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_loull_pb_rpc_LoRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_loull_pb_rpc_LoResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_loull_pb_rpc_LoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025LoullRPCService.proto\022\014loull.pb.rpc\"*\n" +
      "\tLoRequest\022\r\n\005agent\030\001 \002(\t\022\016\n\006thresh\030\002 \002(" +
      "\005\"+\n\nLoResponse\022\016\n\006result\030\001 \002(\005\022\r\n\005alert" +
      "\030\002 \002(\t2M\n\tMyService\022@\n\013loullSample\022\027.lou" +
      "ll.pb.rpc.LoRequest\032\030.loull.pb.rpc.LoRes" +
      "ponseB\"\n\014loull.pb.rpcB\017LoullRPCService\210\001" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_loull_pb_rpc_LoRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_loull_pb_rpc_LoRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_loull_pb_rpc_LoRequest_descriptor,
              new java.lang.String[] { "Agent", "Thresh", });
          internal_static_loull_pb_rpc_LoResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_loull_pb_rpc_LoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_loull_pb_rpc_LoResponse_descriptor,
              new java.lang.String[] { "Result", "Alert", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
